### PR TITLE
Manager/EthernetInterface settings

### PR DESCRIPTION
**Pull request by vranystepan**
I've added a few simple helpers for the configuration of IPv4 parameters.

**methods:**
`get_ilo_ethernet_interface `
`set_ilo_ipv4_dhcp` set iLO to obtain everything from DHCP (IPv4 stack)
`set_ilo_ipv4_static` set static IPv4 address, mask and gateway
`set_ilo_ipv4_dns_servers` set DNS servers
`set_ilo_hostname` set iLO hostname and domain name

**Open topics:**
- [x] unit tests
- [x] documentation (if needed)

### CODE REVIEW

**Review by jsmartt — APPROVED** [review]
These look good! :) Just a thought though... I know we're not using named parameters (keyword arguments) as a standard across the library, but I'm wondering if we should start with these sorts of new features. Seems like they would do well with most (if not all) of these methods. Thoughts @vranystepan ?

**Comment by vranystepan** [comment]
@jsmartt Yeah, it'll work with all these methods I guess. I will do a few more commits tomorrow, good idea!

**Comment by vranystepan** [comment]
@jsmartt I could not wait until tomorrow. However I had to edit Rubocop config because by default it was validating with 2.0 parser so it was complaining about these keyword arguments ... strange. 

```
AllCops:
  TargetRubyVersion: 2.1
```

**Review by jsmartt — APPROVED** [review]
👍

**Comment by jsmartt** [comment]
Are you done working on this @vranystepan ?

**Comment by vranystepan** [comment]
@jsmartt  yes I am

**Comment by jsmartt** [comment]
OK, the last thing would be to bump the [version](https://github.com/HewlettPackard/ilo-sdk-ruby/blob/master/lib/ilo-sdk/version.rb). I think `1.3.0` is the correct version

**Comment by jsmartt** [comment]
Just release 1.3.0! 🎉

**Pull request merged**
