### PR TITLE
added proxy_addr and proxy_host options in Client

### PR DESCRIPTION
**Pull request by Anirudh-Gupta**

### CODE REVIEW

**Comment by bikbajwa** [comment]
Hey Anirudh, I think we want to add a `no_proxy` rather than a proxy to the client. Ruby automatically reads the proxy from environment variables but it does not do so for the `no_proxy`. Essentially, we would pass in a true/false value to set the proxies as `nil`.

**Comment by Anirudh-Gupta** [comment]
@bikbajwa: I think a user(like me) may not set the http_proxy environment variable to use the proxy and reaching to the iLO may(quite unlikely) need the proxy. It would be nice if the user could set the proxy when he is creating the iLO client. If he is not setting it, its nil. 
Also, Net::Http doesn't give us the way to set no_proxy. Please let me know if you can find a way.

**Comment by bikbajwa** [comment]
@Anirudh-Gupta should the setting be nil if it is not provided or should it keep defaulting to the environment variable `HTTP_PROXY`?

**Comment by Anirudh-Gupta** [comment]
@bikbajwa I feel it should be nil if its not set. And if the user wants to, he can(while creating the iLO client) and the same will be used while making requests to the iLO. Should not depend on the environment variable for it. Your thoughts?? Also @jsmartt ?

**Comment by jsmartt** [comment]
I think the best way to go about this would be to let the SDK use the proxy if it's set (as an environment variable), but allow them to explicitly build a client that does not use that proxy (ie a `:disable_proxy` option).

For example:

```ruby
client = ILO_SDK::Client.new(
  host: 'https://ilo.example.com',
  password: 'secret123',
  disable_proxy: true
)
```

And in rest.rb :

```ruby
http = @disable_proxy ? Net::HTTP.new(uri.host, uri.port, nil, nil) : Net::HTTP.new(uri.host, uri.port)
```

This way if they don't set `disable_proxy` to true, it uses the http_proxy env var, but they can also explicitly disable it. That was the real issue in #12 : being able to disable the proxy for a client.

**Comment by Anirudh-Gupta** [comment]
This is also cool. But sometimes a user don't even care/know whether the proxy has been set or not. I am one among them. Will have to check if its enabled via the environment variable and then have to use the disable proxy option.
Either way is good though. Just thinking as a lazy guy.

**Comment by bikbajwa** [comment]
I think having the disable_proxy will be easier than the manual specification of a proxy. Thinking lasy as well :smile:

**Comment by jsmartt** [comment]
I put up a new PR (#16) with the disable_proxy option. Let me know what you guys think.

**Pull request closed without merging**
